<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>1.9.1.2</AssemblyVersion>
    <FileVersion>1.9.1.2</FileVersion>
    <Version>1.9.1.2</Version>
    <RootNamespace>Moonfin.Server</RootNamespace>
    <AssemblyName>Moonfin.Server</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0-rc2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="12.0.0-rc2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\loader.js" />
    <EmbeddedResource Include="Web\inject.html" />
    <EmbeddedResource Include="Pages\configPage.html" />
    <EmbeddedResource Include="assets\*.png" />
    <EmbeddedResource Include="assets\*.svg" />
  </ItemGroup>

</Project>
